---
# Source: kafka/templates/service-headless.yaml
apiVersion: v1
kind: Service
metadata:
  name: kafka-headless
  labels:
    app: kafka
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  ports:
    - name: broker
      port: 9092
  clusterIP: None
  selector:
    app: kafka
