---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kafka

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: kafka
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - patch

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: kafka
roleRef:
  kind: Role
  name: kafka
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: kafka
