apiVersion: v1
kind: Service
metadata:
  name: results
  annotations:
    # Note that the backend talks over HTTP.
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
  labels:
    app: results
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app : results
  type: LoadBalancer
