apiVersion: v1
kind: ReplicationController
metadata:
  name: results
  labels:
    app: results
spec:
  selector:
    app: results
  replicas: 3
  template:
    metadata:
      name: results
      labels:
        app: results
    spec:
      containers:
      - name: results
        image: numberouane2001/meetup-getresults
        ports:
        - name: http-server
          containerPort: 8081

